name: deploy blog to gitee
 
on:
  push:
    branches:
      - master
      
jobs:
  # gitee sync job
  gitee-sync:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Gitee
      uses: wearerequired/git-mirror-action@master
      env:
        SSH_PRIVATE_KEY: ${{ secrets.GITEE_DEPLOY_PRI_KEY }}
      with:
        source-repo: "git@github.com:Rukawalee/rukawalee.github.io.git"
        destination-repo: "git@gitee.com:rukawalee/rukawalee.git"

  # reload gitee page
  gitee-reload-pages:
    needs: gitee-sync
    runs-on: ubuntu-latest
    steps:
      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: Rukawalee
          gitee-password: ${{ secrets.GITEE_PWD }}
          gitee-repo: Rukawalee/Rukawalee
          # branch: gh-pages-gitee
